branch-defaults:
  default:
    environment: Kvisapartner-production
environment-defaults:
  Kvisapartner-production:
    branch: null
    repository: null
global:
  application_name: kvisa_partner
  default_ec2_keyname: kvisadev
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
