# Generated by Django 5.2.2 on 2025-06-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, unique=True, verbose_name='이메일')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='이름')),
                ('log_method', models.IntegerField(choices=[(0, '카카오'), (1, '페이스북'), (2, '구글')], default=0)),
                ('tel_first', models.CharField(max_length=20, null=True, verbose_name='연락처')),
                ('sign_in', models.DateTimeField(auto_now_add=True, verbose_name='회원가입일')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='로그인')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
