# Generated by Django 5.2.2 on 2025-06-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='로그인'),
        ),
        migrations.AlterField(
            model_name='user',
            name='log_method',
            field=models.IntegerField(blank=True, choices=[(0, '카카오'), (1, '페이스북'), (2, '구글')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign_in',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='회원가입일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_first',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처'),
        ),
    ]
